export const difficultyFour = [
    { id: 1, userStack: [["M","Č"], [], ["Z"]], targetStack: [["Č"], ["Z","M"], []], targetMoves: 4 },
    { id: 2, userStack: [["M","Č"], [], ["Z"]], targetStack: [["Č"], ["Z"], ["M"]], targetMoves: 4 },
    { id: 3, userStack: [["M","Č"], [], ["Z"]], targetStack: [["Z","M"], ["Č"], []], targetMoves: 4 },
    { id: 4, userStack: [["M","Č"], [], ["Z"]], targetStack: [["Z"], ["Č"], ["M"]], targetMoves: 4 },
    { id: 5, userStack: [[], ["Z","M"], ["Č"]], targetStack: [["Č","Z"], ["M"], []], targetMoves: 4 },
    { id: 6, userStack: [[], ["Z","M"], ["Č"]], targetStack: [["M"], ["Č","Z"], []], targetMoves: 4 },
    { id: 7, userStack: [[], ["Z","M"], ["Č"]], targetStack: [["Č"], ["M"], ["Z"]], targetMoves: 4 },
    { id: 8, userStack: [[], ["Z","M"], ["Č"]], targetStack: [["Č","Z","M"], [], []], targetMoves: 4 },
    { id: 9, userStack: [[], ["Z","M"], ["Č"]], targetStack: [["M"], ["Č"], ["Z"]], targetMoves: 4 },
    { id: 10, userStack: [["Č","Z"], ["M"], []], targetStack: [[], ["Z","M"], ["Č"]], targetMoves: 4 },
    { id: 11, userStack: [["Č","Z"], ["M"], []], targetStack: [["Z","Č"], ["M"], []], targetMoves: 4 },
    { id: 12, userStack: [["Č","Z"], ["M"], []], targetStack: [["Z","M"], [], ["Č"]], targetMoves: 4 },
    { id: 13, userStack: [["Č","Z"], ["M"], []], targetStack: [["M"], ["Z","Č"], []], targetMoves: 4 },
    { id: 14, userStack: [[], ["Č","Z"], ["M"]], targetStack: [["Z"], ["M","Č"], []], targetMoves: 4 },
    { id: 15, userStack: [[], ["Č","Z"], ["M"]], targetStack: [["Z"], ["M"], ["Č"]], targetMoves: 4 },
    { id: 16, userStack: [[], ["Č","Z"], ["M"]], targetStack: [["M","Č"], ["Z"], []], targetMoves: 4 },
    { id: 17, userStack: [[], ["Č","Z"], ["M"]], targetStack: [["M"], ["Z"], ["Č"]], targetMoves: 4 },
    { id: 18, userStack: [[], ["Č","Z"], ["M"]], targetStack: [["M","Č","Z"], [], []], targetMoves: 4 },
    { id: 19, userStack: [["M"], ["Č","Z"], []], targetStack: [[], ["Z","M"], ["Č"]], targetMoves: 4 },
    { id: 20, userStack: [["M"], ["Č","Z"], []], targetStack: [["Z","Č"], ["M"], []], targetMoves: 4 },
];

export const difficultyFive = [
    { id: 1, userStack: [["M","Č"], [], ["Z"]], targetStack: [["Č","Z"], [], ["M"]], targetMoves: 5 },
    { id: 2, userStack: [["M","Č"], [], ["Z"]], targetStack: [["Z","Č"], [], ["M"]], targetMoves: 5 },
    { id: 3, userStack: [["M","Č"], [], ["Z"]], targetStack: [["Č","M"], ["Z"], []], targetMoves: 5 },
    { id: 4, userStack: [["M","Č"], [], ["Z"]], targetStack: [["Z","M"], [], ["Č"]], targetMoves: 5 },
    { id: 5, userStack: [["M","Č"], [], ["Z"]], targetStack: [["Z","M","Č"], [], []], targetMoves: 5 },
    { id: 6, userStack: [[], ["Z","M"], ["Č"]], targetStack: [[], ["Č","Z"], ["M"]], targetMoves: 5 },
    { id: 7, userStack: [[], ["Z","M"], ["Č"]], targetStack: [[], ["Č","M"], ["Z"]], targetMoves: 5 },
    { id: 8, userStack: [[], ["Z","M"], ["Č"]], targetStack: [[], ["M","Č"], ["Z"]], targetMoves: 5 },
    { id: 9, userStack: [[], ["Z","M"], ["Č"]], targetStack: [["Č"], ["M","Z"], []], targetMoves: 5 },
    { id: 10, userStack: [["Č","Z"], ["M"], []], targetStack: [["Z","Č"], [], ["M"]], targetMoves: 5 },
    { id: 11, userStack: [["Č","Z"], ["M"], []], targetStack: [["Z","M"], ["Č"], []], targetMoves: 5 },
    { id: 12, userStack: [["Č","Z"], ["M"], []], targetStack: [["Z","M","Č"], [], []], targetMoves: 5 },
    { id: 13, userStack: [["Č","Z"], ["M"], []], targetStack: [["M","Č"], ["Z"], []], targetMoves: 5 },
    { id: 14, userStack: [["Č","Z"], ["M"], []], targetStack: [["Z","Č","M"], [], []], targetMoves: 5 },
    { id: 15, userStack: [["Č","Z"], ["M"], []], targetStack: [["M"], ["Z"], ["Č"]], targetMoves: 5 },
    { id: 16, userStack: [[], ["Č","Z"], ["M"]], targetStack: [[], ["Z","M"], ["Č"]], targetMoves: 5 },
    { id: 17, userStack: [[], ["Č","Z"], ["M"]], targetStack: [["M"], ["Z","Č"], []], targetMoves: 5 },
    { id: 18, userStack: [[], ["Č","Z"], ["M"]], targetStack: [[], ["M","Z"], ["Č"]], targetMoves: 5 },
    { id: 19, userStack: [[], ["Č","Z"], ["M"]], targetStack: [[], ["M","Č"], ["Z"]], targetMoves: 5 },
    { id: 20, userStack: [["M"], ["Č","Z"], []], targetStack: [["Č"], ["Z","M"], []], targetMoves: 5 },
];

export const difficultySix = [
    { id: 1, userStack: [["M","Č"], [], ["Z"]], targetStack: [["Č","Z"], ["M"], []], targetMoves: 6 },
    { id: 2, userStack: [["M","Č"], [], ["Z"]], targetStack: [["Z","Č"], ["M"], []], targetMoves: 6 },
    { id: 3, userStack: [["M","Č"], [], ["Z"]], targetStack: [["Č","M"], [], ["Z"]], targetMoves: 6 },
    { id: 4, userStack: [["M","Č"], [], ["Z"]], targetStack: [["Z"], ["M"], ["Č"]], targetMoves: 6 },
    { id: 5, userStack: [["M","Č"], [], ["Z"]], targetStack: [["Č","M","Z"], [], []], targetMoves: 6 },
    { id: 6, userStack: [["M","Č"], [], ["Z"]], targetStack: [["Č","Z","M"], [], []], targetMoves: 6 },
    { id: 7, userStack: [["M","Č"], [], ["Z"]], targetStack: [["Z","Č","M"], [], []], targetMoves: 6 },
    { id: 8, userStack: [[], ["Z","M"], ["Č"]], targetStack: [["Z"], ["M","Č"], []], targetMoves: 6 },
    { id: 9, userStack: [[], ["Z","M"], ["Č"]], targetStack: [["Z"], ["Č"], ["M"]], targetMoves: 6 },
    { id: 10, userStack: [[], ["Z","M"], ["Č"]], targetStack: [[], ["M","Z"], ["Č"]], targetMoves: 6 },
    { id: 11, userStack: [[], ["Z","M"], ["Č"]], targetStack: [["Z"], ["Č","M"], []], targetMoves: 6 },
    { id: 12, userStack: [["Č","Z"], ["M"], []], targetStack: [["M","Č"], [], ["Z"]], targetMoves: 6 },
    { id: 13, userStack: [["Č","Z"], ["M"], []], targetStack: [["M","Z"], [], ["Č"]], targetMoves: 6 },
    { id: 14, userStack: [["Č","Z"], ["M"], []], targetStack: [["Z"], ["Č"], ["M"]], targetMoves: 6 },
    { id: 15, userStack: [["Č","Z"], ["M"], []], targetStack: [["Z"], ["Č","M"], []], targetMoves: 6 },
    { id: 16, userStack: [["Č","Z"], ["M"], []], targetStack: [["M","Č","Z"], [], []], targetMoves: 6 },
    { id: 17, userStack: [[], ["Č","Z"], ["M"]], targetStack: [["Č"], ["Z","M"], []], targetMoves: 6 },
    { id: 18, userStack: [[], ["Č","Z"], ["M"]], targetStack: [["Č"], ["M"], ["Z"]], targetMoves: 6 },
    { id: 19, userStack: [[], ["Č","Z"], ["M"]], targetStack: [[], ["Z","Č"], ["M"]], targetMoves: 6 },
    { id: 20, userStack: [[], ["Č","Z"], ["M"]], targetStack: [["Č"], ["M","Z"], []], targetMoves: 6 },
];